name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request: {}
  schedule:
    - cron:  '0 3 * * *' # daily, at 3am

env:
  VOLTA_FEATURE_PNPM: 1

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true


jobs:
  lint-addon:
    name: Lint Addon
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/pnpm-setup
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint:addon

  lint-test-app:
    name: Lint Test App
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/pnpm-setup
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint:test-app

  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        test-suite:
          - ember-4.0
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-4.12
          - ember-default
          - ember-release
          - embroider-safe
          - embroider-optimized
        allow-failure: [false]
        include:
           - test-suite: ember-canary
             allow-failure: true
           - test-suite: ember-beta
             allow-failure: true

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/pnpm-setup
      - name: Install dependencies
        run: pnpm install
      - name: tests
        run: pnpm test:test-app ${{ matrix.test-suite }}
        continue-on-error: ${{matrix.allow-failure}}

  extra-tests:
    name: Tests (Floating Dependencies)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: ./.github/actions/pnpm-setup
      - name: Install dependencies
        run: pnpm install --no-lockfile

      - name: tests
        run: pnpm test
        continue-on-error: true
